language: python
python: 3.6
cache: pip
env:
  global:
  # AWS_ACCESS_KEY_ID bloop-integ-travis-001
  - secure: fw6+R5mHzcpaex9kmLwWo8DsxlsWGpGBlyKfsPDf7qSqgkLjli65zDiMKKTLKyRzXWo4N3e2VerKY1kZScejPjl2c6i/aGOONsADooH3qQi9/ic1gBwmNOiZwNRgtBgicV3FlL0VukriPtnhO+D7YZGn700JkXxFxu6BCzafBdM=
  # AWS_SECRET_ACCESS_KEY bloop-integ-travis-001
  - secure: HiDY8j0bQoPD0dQ5dVn5jaXxQlp/prb1B80Yz9Ji0Ea7KaU+BOA9EoIrVL3lhB7sS9P2R2Mz5nH4z8Yhur76oRfrkHzkn+9AfXmv/KTVSl0tLFZ2kXCGPMa+LYIwt6JlsKNtgkyufs/mGWYZc84sQolA/9G/b0lusAsp/WU67ts=
  matrix:
  - TOXENV=unit
  - TOXENV=integ
  - TOXENV=docs
install: pip install tox codecov
script: scripts/travis_script.sh
after_success:
- test $TOXENV = "unit" && codecov
- test $TOXENV = "integ" && codecov
notifications:
  slack:
    secure: cXjzhmFI0oAWifBilGvTApiL8VSyM7/4v3Ve4TZeU+15EoYf05AhNoHs0FKVcj+ockYPqlj3p+SIUXnGfcI41QFlO09gGvFVB/FA/PHH2n4hb20+zxSx5Ic9ac3B2Nb5u2lWGsSsRTvCHtC0Wcxx878ML5UFrP5yu4vKIgj8AyE=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/12807f3b2c9083de2e36
    on_success: change
    on_failure: always
    on_start: never
# container-based for faster builds
sudo: false
# tls 1.2
dist: trusty
